
tasks:
  - init: yarn install && yarn run build
    command: yarn run test

vscode:
  extensions:
    - usernamehw.errorlens
    - dbaeumer.vscode-eslint
    - tamasfe.even-better-toml
    - esbenp.prettier-vscode
    - rvest.vs-code-prettier-eslint
    - matklad.rust-analyzer
    - gengjiawen.vscode-wasm
